### ISSUE TITLE
Update the CheriABI "Hello World" example to use GDB 12

### ISSUE THREAD

**Issue by kwitaszczyk** [CTSRD-CHERI/cheribsd-getting-started#24]
The example should present tag information and disassembler from GDB 12.

**Comment by nwf** [comment]
Similar changes would probably be good for https://github.com/CTSRD-CHERI/cheri-exercises

**Comment by brooksdavis** [comment]
I've created https://github.com/CTSRD-CHERI/cheri-exercises/issues/51
