### ISSUE TITLE
Update the guide to 23.1M

### ISSUE THREAD

**Issue by kwitaszczyk** [CTSRD-CHERI/cheribsd-getting-started#40]
- [x] Bump the CheriBSD version in all places (grep for `22.12`)
- [x] Merge https://github.com/CTSRD-CHERI/cheribsd-getting-started/pull/35
- [x] Merge #41 
- [x] Merge https://github.com/CTSRD-CHERI/cheribsd-getting-started/pull/47
- [x] Merge https://github.com/CTSRD-CHERI/cheribsd-getting-started/pull/45
- [x] Merge https://github.com/CTSRD-CHERI/cheribsd-getting-started/pull/46
- [x] #49

**Comment by rwatson** [comment]
Also #41.

**Comment by kwitaszczyk** [comment]
All PRs have been merged.
